function stemp(station, chartSettings) {

    var stemp_historical = AmCharts.makeChart("stemp_historical", {
        "type": "serial",
        "theme": "dark",
        "marginRight": 30,
        "autoMarginOffset": 20,
        "synchronizeGrid": chartSettings.synchronizeGrid,		
        "marginTop": 7,
        "legend": {
            "equalWidths": true,
            "useGraphSettings": true,
            "align": "left",
            "valueAlign": "left",
            "valueText": "[[value]] °C",
            "valueWidth": 100
        },
        "titles": [{
            "text": "Historical (daily means)",
            "color": "#E8E8E8",
            "size": 16
        }],
        "dataLoader": {
            "id": "file1",
            "url": "https://www.wsl.ch/gcnet/data/" + station + "stemp.json"
        },
        "mouseWheelZoomEnabled": false,
        "graphs": [{
                "id": "stempHistorical1",
                "balloonText": "[[category]]<br/><b><span style='font-size:14px;'>1: [[value]] °C</span></b>",
                "bullet": "round",
				"bulletBorderAlpha": chartSettings.bulletBorderAlpha,
				"bulletAlpha": chartSettings.bulletAlpha,
				"bulletSize": chartSettings.bulletSize,
				"lineThickness": chartSettings.lineThickness,
                "startDuration": 1,
                "gridAboveGraphs": true,
                "clustered": false,
                "fillAlphas": 0,
                "type": "line",
                "connect": false,
                "bulletColor": "#D1D3FF",
                "hideBulletsCount": 500,
                "title": "1",
                "valueField": "SnowT1",
                "lineColor": "#D1D3FF",
                "useLineColorForBulletBorder": true
            },
            {
                "id": "stempHistorical2",
                "balloonText": "[[category]]<br/><b><span style='font-size:14px;'>2: [[value]] °C</span></b>",
                "bullet": "round",
				"bulletBorderAlpha": chartSettings.bulletBorderAlpha,
				"bulletAlpha": chartSettings.bulletAlpha,
				"bulletSize": chartSettings.bulletSize,
				"lineThickness": chartSettings.lineThickness,
                "startDuration": 1,
                "gridAboveGraphs": true,
                "clustered": false,
                "fillAlphas": 0,
                "type": "line",
                "connect": false,
                "bulletColor": "#B9BCF3",
                "hideBulletsCount": 500,
                "title": "2",
                "valueField": "SnowT2",
                "lineColor": "#B9BCF3",
                "useLineColorForBulletBorder": true
            },
            {
                "id": "stempHistorical3",
                "balloonText": "[[category]]<br/><b><span style='font-size:14px;'>3: [[value]] °C</span></b>",
                "bullet": "round",
				"bulletBorderAlpha": chartSettings.bulletBorderAlpha,
				"bulletAlpha": chartSettings.bulletAlpha,
				"bulletSize": chartSettings.bulletSize,
				"lineThickness": chartSettings.lineThickness,
                "startDuration": 1,
                "gridAboveGraphs": true,
                "clustered": false,
                "fillAlphas": 0,
                "type": "line",
                "connect": false,
                "bulletColor": "#A2A5E7",
                "hideBulletsCount": 500,
                "title": "3",
                "valueField": "SnowT3",
                "lineColor": "#A2A5E7",
                "useLineColorForBulletBorder": true
            },
            {
                "id": "stempHistorical4",
                "balloonText": "[[category]]<br/><b><span style='font-size:14px;'>4: [[value]] °C</span></b>",
                "bullet": "round",
				"bulletBorderAlpha": chartSettings.bulletBorderAlpha,
				"bulletAlpha": chartSettings.bulletAlpha,
				"bulletSize": chartSettings.bulletSize,
				"lineThickness": chartSettings.lineThickness,
                "startDuration": 1,
                "gridAboveGraphs": true,
                "clustered": false,
                "fillAlphas": 0,
                "type": "line",
                "connect": false,
                "bulletColor": "#8B8FDB",
                "hideBulletsCount": 500,
                "title": "4",
                "valueField": "SnowT4",
                "lineColor": "#8B8FDB",
                "useLineColorForBulletBorder": true
            },
            {
                "id": "stempHistorical5",
                "balloonText": "[[category]]<br/><b><span style='font-size:14px;'>5: [[value]] °C</span></b>",
                "bullet": "round",
				"bulletBorderAlpha": chartSettings.bulletBorderAlpha,
				"bulletAlpha": chartSettings.bulletAlpha,
				"bulletSize": chartSettings.bulletSize,
				"lineThickness": chartSettings.lineThickness,
                "startDuration": 1,
                "gridAboveGraphs": true,
                "clustered": false,
                "fillAlphas": 0,
                "type": "line",
                "connect": false,
                "bulletColor": "#7478CF",
                "hideBulletsCount": 500,
                "title": "5",
                "valueField": "SnowT5",
                "lineColor": "#7478CF",
                "useLineColorForBulletBorder": true
            },
            {
                "id": "stempHistorical6",
                "balloonText": "[[category]]<br/><b><span style='font-size:14px;'>6: [[value]] °C</span></b>",
                "bullet": "round",
				"bulletBorderAlpha": chartSettings.bulletBorderAlpha,
				"bulletAlpha": chartSettings.bulletAlpha,
				"bulletSize": chartSettings.bulletSize,
				"lineThickness": chartSettings.lineThickness,
                "startDuration": 1,
                "gridAboveGraphs": true,
                "clustered": false,
                "fillAlphas": 0,
                "type": "line",
                "connect": false,
                "bulletColor": "#5C61C3",
                "hideBulletsCount": 500,
                "title": "6",
                "valueField": "SnowT6",
                "lineColor": "#5C61C3",
                "useLineColorForBulletBorder": true
            },
            {
                "id": "stempHistorical7",
                "balloonText": "[[category]]<br/><b><span style='font-size:14px;'>7: [[value]] °C</span></b>",
                "bullet": "round",
				"bulletBorderAlpha": chartSettings.bulletBorderAlpha,
				"bulletAlpha": chartSettings.bulletAlpha,
				"bulletSize": chartSettings.bulletSize,
				"lineThickness": chartSettings.lineThickness,
                "startDuration": 1,
                "gridAboveGraphs": true,
                "clustered": false,
                "fillAlphas": 0,
                "type": "line",
                "connect": false,
                "bulletColor": "#454BB7",
                "hideBulletsCount": 500,
                "title": "7",
                "valueField": "SnowT7",
                "lineColor": "#454BB7",
                "useLineColorForBulletBorder": true
            },
            {
                "id": "stempHistorical8",
                "balloonText": "[[category]]<br/><b><span style='font-size:14px;'>8: [[value]] °C</span></b>",
                "bullet": "round",
				"bulletBorderAlpha": chartSettings.bulletBorderAlpha,
				"bulletAlpha": chartSettings.bulletAlpha,
				"bulletSize": chartSettings.bulletSize,
				"lineThickness": chartSettings.lineThickness,
                "startDuration": 1,
                "gridAboveGraphs": true,
                "clustered": false,
                "fillAlphas": 0,
                "type": "line",
                "connect": false,
                "bulletColor": "#2E34AB",
                "hideBulletsCount": 500,
                "title": "8",
                "valueField": "SnowT8",
                "lineColor": "#2E34AB",
                "useLineColorForBulletBorder": true
            },
            {
                "id": "stempHistorical9",
                "balloonText": "[[category]]<br/><b><span style='font-size:14px;'>9: [[value]] °C</span></b>",
                "bullet": "round",
				"bulletBorderAlpha": chartSettings.bulletBorderAlpha,
				"bulletAlpha": chartSettings.bulletAlpha,
				"bulletSize": chartSettings.bulletSize,
				"lineThickness": chartSettings.lineThickness,
                "startDuration": 1,
                "gridAboveGraphs": true,
                "clustered": false,
                "fillAlphas": 0,
                "type": "line",
                "connect": false,
                "bulletColor": "#171D9F",
                "hideBulletsCount": 500,
                "title": "9",
                "valueField": "SnowT9",
                "lineColor": "#171D9F",
                "useLineColorForBulletBorder": true
            },
            {
                "id": "stempHistorical10",
                "balloonText": "[[category]]<br/><b><span style='font-size:14px;'>10: [[value]] °C</span></b>",
                "bullet": "round",
				"bulletBorderAlpha": chartSettings.bulletBorderAlpha,
				"bulletAlpha": chartSettings.bulletAlpha,
				"bulletSize": chartSettings.bulletSize,
				"lineThickness": chartSettings.lineThickness,
                "startDuration": 1,
                "gridAboveGraphs": true,
                "clustered": false,
                "fillAlphas": 0,
                "type": "line",
                "connect": false,
                "bulletColor": "#000794",
                "hideBulletsCount": 500,
                "title": "10",
                "valueField": "SnowT10",
                "lineColor": "#000794",
                "useLineColorForBulletBorder": true
            }
        ],
        "chartScrollbar": {
            "oppositeAxis": false,
            "offset": 30,
            "scrollbarHeight": 20,
            "backgroundAlpha": 0,
            "selectedBackgroundAlpha": 0.1,
            "selectedBackgroundColor": "#888888",
            "graphFillAlpha": 0,
            "graphLineAlpha": 0.5,
            "selectedGraphFillAlpha": 0,
            "selectedGraphLineAlpha": 1,
            "autoGridCount": true,
            "color": "#AAAAAA"
        },
        "chartCursor": {
            "pan": false,
            "valueLineEnabled": true,
            "valueLineBalloonEnabled": true,
            "parseDates": true,
            "categoryBalloonDateFormat": "MMM DD, YYYY",
            "dataDateFormat": "MMM DD, YYYY"
        },
        "categoryField": "timestamp",
        "categoryAxis": {
            "parseDates": true,
            "minPeriod": "ww",
            "equalSpacing": true,
            "axisColor": "#DADADA",
            "dashLength": 1,
            "minorGridEnabled": true
        },
        "valueAxes": [{
            "axisAlpha": 0.2,
            "unit": " °C",
            "dashLength": 1,
            "position": "left"
        }]
    });



    var stemp_recentDays = AmCharts.makeChart("stemp_recentDays", {
        "type": "serial",
        "theme": "dark",
        "marginRight": 30,
        "autoMarginOffset": 20,
        "synchronizeGrid": chartSettings.synchronizeGrid,		
        "marginTop": 7,
        "legend": {
            "equalWidths": true,
            "useGraphSettings": true,
            "align": "left",
            "valueAlign": "left",
            "valueText": "[[value]] °C",
            "valueWidth": 100
        },
        "titles": [{
            "text": "Past 14 days",
            "color": "#E8E8E8",
            "size": 16
        }],
        "dataLoader": {
            "id": "file1",
            "url": "https://www.wsl.ch/gcnet/data/" + station + "stemp_v.json",
        },
        "mouseWheelZoomEnabled": false,
	 "graphs": [{
                "id": "stempRecent1",
                "balloonText": "[[category]]<br/><b><span style='font-size:14px;'>1: [[value]] °C</span></b>",
                "bullet": "round",
				"bulletBorderAlpha": chartSettings.bulletBorderAlpha,
				"bulletAlpha": chartSettings.bulletAlpha,
				"bulletSize": chartSettings.bulletSize,
				"lineThickness": chartSettings.lineThickness,
                "startDuration": 1,
                "gridAboveGraphs": true,
                "clustered": false,
                "fillAlphas": 0,
                "type": "line",
                "connect": false,
                "bulletColor": "#D1D3FF",
                "hideBulletsCount": 500,
                "title": "1",
                "valueField": "SnowT1",
                "lineColor": "#D1D3FF",
                "useLineColorForBulletBorder": true
            },
            {
                "id": "stempRecent2",
                "balloonText": "[[category]]<br/><b><span style='font-size:14px;'>2: [[value]] °C</span></b>",
                "bullet": "round",
				"bulletBorderAlpha": chartSettings.bulletBorderAlpha,
				"bulletAlpha": chartSettings.bulletAlpha,
				"bulletSize": chartSettings.bulletSize,
				"lineThickness": chartSettings.lineThickness,
                "startDuration": 1,
                "gridAboveGraphs": true,
                "clustered": false,
                "fillAlphas": 0,
                "type": "line",
                "connect": false,
                "bulletColor": "#B9BCF3",
                "hideBulletsCount": 500,
                "title": "2",
                "valueField": "SnowT2",
                "lineColor": "#B9BCF3",
                "useLineColorForBulletBorder": true
            },
            {
                "id": "stempRecent3",
                "balloonText": "[[category]]<br/><b><span style='font-size:14px;'>3: [[value]] °C</span></b>",
                "bullet": "round",
				"bulletBorderAlpha": chartSettings.bulletBorderAlpha,
				"bulletAlpha": chartSettings.bulletAlpha,
				"bulletSize": chartSettings.bulletSize,
				"lineThickness": chartSettings.lineThickness,
                "startDuration": 1,
                "gridAboveGraphs": true,
                "clustered": false,
                "fillAlphas": 0,
                "type": "line",
                "connect": false,
                "bulletColor": "#A2A5E7",
                "hideBulletsCount": 500,
                "title": "3",
                "valueField": "SnowT3",
                "lineColor": "#A2A5E7",
                "useLineColorForBulletBorder": true
            },
            {
                "id": "stempRecent4",
                "balloonText": "[[category]]<br/><b><span style='font-size:14px;'>4: [[value]] °C</span></b>",
                "bullet": "round",
				"bulletBorderAlpha": chartSettings.bulletBorderAlpha,
				"bulletAlpha": chartSettings.bulletAlpha,
				"bulletSize": chartSettings.bulletSize,
				"lineThickness": chartSettings.lineThickness,
                "startDuration": 1,
                "gridAboveGraphs": true,
                "clustered": false,
                "fillAlphas": 0,
                "type": "line",
                "connect": false,
                "bulletColor": "#8B8FDB",
                "hideBulletsCount": 500,
                "title": "4",
                "valueField": "SnowT4",
                "lineColor": "#8B8FDB",
                "useLineColorForBulletBorder": true
            },
            {
                "id": "stempRecent5",
                "balloonText": "[[category]]<br/><b><span style='font-size:14px;'>5: [[value]] °C</span></b>",
                "bullet": "round",
				"bulletBorderAlpha": chartSettings.bulletBorderAlpha,
				"bulletAlpha": chartSettings.bulletAlpha,
				"bulletSize": chartSettings.bulletSize,
				"lineThickness": chartSettings.lineThickness,
                "startDuration": 1,
                "gridAboveGraphs": true,
                "clustered": false,
                "fillAlphas": 0,
                "type": "line",
                "connect": false,
                "bulletColor": "#7478CF",
                "hideBulletsCount": 500,
                "title": "5",
                "valueField": "SnowT5",
                "lineColor": "#7478CF",
                "useLineColorForBulletBorder": true
            },
            {
                "id": "stempRecent6",
                "balloonText": "[[category]]<br/><b><span style='font-size:14px;'>6: [[value]] °C</span></b>",
                "bullet": "round",
				"bulletBorderAlpha": chartSettings.bulletBorderAlpha,
				"bulletAlpha": chartSettings.bulletAlpha,
				"bulletSize": chartSettings.bulletSize,
				"lineThickness": chartSettings.lineThickness,
                "startDuration": 1,
                "gridAboveGraphs": true,
                "clustered": false,
                "fillAlphas": 0,
                "type": "line",
                "connect": false,
                "bulletColor": "#5C61C3",
                "hideBulletsCount": 500,
                "title": "6",
                "valueField": "SnowT6",
                "lineColor": "#5C61C3",
                "useLineColorForBulletBorder": true
            },
            {
                "id": "stempRecent7",
                "balloonText": "[[category]]<br/><b><span style='font-size:14px;'>7: [[value]] °C</span></b>",
                "bullet": "round",
				"bulletBorderAlpha": chartSettings.bulletBorderAlpha,
				"bulletAlpha": chartSettings.bulletAlpha,
				"bulletSize": chartSettings.bulletSize,
				"lineThickness": chartSettings.lineThickness,
                "startDuration": 1,
                "gridAboveGraphs": true,
                "clustered": false,
                "fillAlphas": 0,
                "type": "line",
                "connect": false,
                "bulletColor": "#454BB7",
                "hideBulletsCount": 500,
                "title": "7",
                "valueField": "SnowT7",
                "lineColor": "#454BB7",
                "useLineColorForBulletBorder": true
            },
            {
                "id": "stempRecent8",
                "balloonText": "[[category]]<br/><b><span style='font-size:14px;'>8: [[value]] °C</span></b>",
                "bullet": "round",
				"bulletBorderAlpha": chartSettings.bulletBorderAlpha,
				"bulletAlpha": chartSettings.bulletAlpha,
				"bulletSize": chartSettings.bulletSize,
				"lineThickness": chartSettings.lineThickness,
                "startDuration": 1,
                "gridAboveGraphs": true,
                "clustered": false,
                "fillAlphas": 0,
                "type": "line",
                "connect": false,
                "bulletColor": "#2E34AB",
                "hideBulletsCount": 500,
                "title": "8",
                "valueField": "SnowT8",
                "lineColor": "#2E34AB",
                "useLineColorForBulletBorder": true
            },
            {
                "id": "stempRecent9",
                "balloonText": "[[category]]<br/><b><span style='font-size:14px;'>9: [[value]] °C</span></b>",
                "bullet": "round",
				"bulletBorderAlpha": chartSettings.bulletBorderAlpha,
				"bulletAlpha": chartSettings.bulletAlpha,
				"bulletSize": chartSettings.bulletSize,
				"lineThickness": chartSettings.lineThickness,
                "startDuration": 1,
                "gridAboveGraphs": true,
                "clustered": false,
                "fillAlphas": 0,
                "type": "line",
                "connect": false,
                "bulletColor": "#171D9F",
                "hideBulletsCount": 500,
                "title": "9",
                "valueField": "SnowT9",
                "lineColor": "#171D9F",
                "useLineColorForBulletBorder": true
            },
            {
                "id": "stempRecent10",
                "balloonText": "[[category]]<br/><b><span style='font-size:14px;'>10: [[value]] °C</span></b>",
                "bullet": "round",
				"bulletBorderAlpha": chartSettings.bulletBorderAlpha,
				"bulletAlpha": chartSettings.bulletAlpha,
				"bulletSize": chartSettings.bulletSize,
				"lineThickness": chartSettings.lineThickness,
                "startDuration": 1,
                "gridAboveGraphs": true,
                "clustered": false,
                "fillAlphas": 0,
                "type": "line",
                "connect": false,
                "bulletColor": "#000794",
                "hideBulletsCount": 500,
                "title": "10",
                "valueField": "SnowT10",
                "lineColor": "#000794",
                "useLineColorForBulletBorder": true
            }
        ],
        "chartScrollbar": {
            "oppositeAxis": false,
            "offset": 30,
            "scrollbarHeight": 20,
            "backgroundAlpha": 0,
            "selectedBackgroundAlpha": 0.1,
            "selectedBackgroundColor": "#888888",
            "graphFillAlpha": 0,
            "graphLineAlpha": 0.5,
            "selectedGraphFillAlpha": 0,
            "selectedGraphLineAlpha": 1,
            "autoGridCount": true,
            "color": "#AAAAAA"
        },
        "chartCursor": {
            "pan": false,
            "valueLineEnabled": true,
            "valueLineBalloonEnabled": true,
            "parseDates": true,
            "categoryBalloonDateFormat": "MMM DD, YYYY JJ:NNZ",
            "dataDateFormat": "MMM DD, YYYY JJ:NNZ"
        },
        "categoryField": "timestamp",
        "categoryAxis": {
            "parseDates": true,
            "minPeriod": "ww",
            "equalSpacing": true,
            "axisColor": "#DADADA",
            "dashLength": 1,
            "minorGridEnabled": true
        },
        "valueAxes": [{
            "axisAlpha": 0.2,
            "unit": " °C",
            "dashLength": 1,
            "position": "left"
        }]
    });
}